name: Run Selenium + Pytest tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Google Chrome v124
      run: |
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.91-1_amd64.deb
        sudo apt install -y ./google-chrome-stable_124.0.6367.91-1_amd64.deb

    - name: Install ChromeDriver v124
      run: |
        wget -q https://chromedriver.storage.googleapis.com/124.0.6367.91/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version
        google-chrome --version

    - name: Start test server
      working-directory: ./dist
      run: python3 -m http.server 8000 &

    - name: Run tests
      run: pytest --tb=short -v
