name: Run Selenium + Pytest tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Setup ChromeDriver
      uses: browser-actions/setup-chromedriver@v1

    - name: Start test server
      working-directory: ./dist
      run: python3 -m http.server 8000 &

    - name: Run tests
      env:
        CHROME_BIN: google-chrome
      run: pytest --tb=short -v
